services:
  app:
    image: php:8.2-apache
    container_name: app
    restart: unless-stopped    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./app_code:/var/www/html/:ro
    networks:
      - backend_net

  # First Nginx (Первый узел) — всегда существует
  nginx1:
    image: nginx:1.27.4-alpine
    container_name: nginx1
    restart: unless-stopped    
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./nginx/nginx-first.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
    networks:
      - backend_net

  # Промежуточные узлы (Генерируются в цикле, если nginx_count > 2)
  nginx2:
    image: nginx:1.27.4-alpine
    container_name: nginx2
    restart: unless-stopped    
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./nginx/nginx2.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8082:80"
    networks:
      - backend_net
  nginx3:
    image: nginx:1.27.4-alpine
    container_name: nginx3
    restart: unless-stopped    
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./nginx/nginx3.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8083:80"
    networks:
      - backend_net
  nginx4:
    image: nginx:1.27.4-alpine
    container_name: nginx4
    restart: unless-stopped    
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./nginx/nginx4.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8084:80"
    networks:
      - backend_net

  # Замыкающий узел (Генерируется, если nginx_count > 1)
  nginx5:
    image: nginx:1.27.4-alpine
    container_name: nginx5
    restart: unless-stopped    
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./nginx/nginx-last.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8085:80"
    networks:
      - backend_net

  load_balancer:
    image: nginx:1.27.4-alpine
    container_name: load_balancer
    restart: unless-stopped  
    ports:
      - "80:80"
    volumes:
      - ./nginx/load_balancer.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nginx1
      - nginx2
      - nginx3
      - nginx4
      - nginx5
    networks:
      - backend_net

networks:
  backend_net:
    ipam:
      config:
        - subnet: 172.20.0.0/16