services:
  app:
    image: php:8.2-apache
    container_name: app
    restart: unless-stopped    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./app_code:/var/www/html/:ro
    networks:
      - backend_net

  nginx1:
    image: nginx:1.27.4-alpine
    container_name: nginx1
    restart: unless-stopped
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/template/default.conf.template:ro
      - ./nginx/my-includes/:/etc/nginx/my-includes/:ro
    ports:
      - "8081:80"
    environment:
      - NEXT_HOP=nginx2
    command: >
      sh -c "envsubst '$${NEXT_HOP}' < /etc/nginx/template/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - backend_net
  nginx2:
    image: nginx:1.27.4-alpine
    container_name: nginx2
    restart: unless-stopped
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/template/default.conf.template:ro
      - ./nginx/my-includes/:/etc/nginx/my-includes/:ro
    ports:
      - "8082:80"
    environment:
      - NEXT_HOP=nginx3
    command: >
      sh -c "envsubst '$${NEXT_HOP}' < /etc/nginx/template/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - backend_net
  nginx3:
    image: nginx:1.27.4-alpine
    container_name: nginx3
    restart: unless-stopped
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/template/default.conf.template:ro
      - ./nginx/my-includes/:/etc/nginx/my-includes/:ro
    ports:
      - "8083:80"
    environment:
      - NEXT_HOP=nginx4
    command: >
      sh -c "envsubst '$${NEXT_HOP}' < /etc/nginx/template/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - backend_net
  nginx4:
    image: nginx:1.27.4-alpine
    container_name: nginx4
    restart: unless-stopped
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/template/default.conf.template:ro
      - ./nginx/my-includes/:/etc/nginx/my-includes/:ro
    ports:
      - "8084:80"
    environment:
      - NEXT_HOP=nginx5
    command: >
      sh -c "envsubst '$${NEXT_HOP}' < /etc/nginx/template/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - backend_net
  nginx5:
    image: nginx:1.27.4-alpine
    container_name: nginx5
    restart: unless-stopped
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/template/default.conf.template:ro
      - ./nginx/my-includes/:/etc/nginx/my-includes/:ro
    ports:
      - "8085:80"
    environment:
      - NEXT_HOP=app
    command: >
      sh -c "envsubst '$${NEXT_HOP}' < /etc/nginx/template/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - backend_net

  load_balancer:
    image: nginx:1.27.4-alpine
    container_name: load_balancer
    restart: unless-stopped  
    ports:
      - "80:80"
    volumes:
      - ./nginx/load_balancer.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/my-includes/:/etc/nginx/my-includes/:ro      

    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge