geo $is_trusted {
    default 0;
    
    10.0.0.0/8 1; 
    172.16.0.0/12 1;
    192.168.0.0/16 1;
}

# Формируем чистый IP пользователя
map $is_trusted $temp_client_ip {
    0       $remote_addr;
    1       $http_x_real_ip;
}

map $temp_client_ip $first_client_ip {
    ""      $remote_addr;
    default $temp_client_ip;
}