resolver 127.0.0.11 valid=1s;

# Запрос пришел извне 1 или из предыдущей цепочки 0?


# Определяем, куда идем: на app или в цепочку, сделал 50/50, рандомно
split_clients "${request_id}" $route {
    50%             "app";
    *               "nginx3";
}

map $http_x_internal_chain $dynamic_target {
    ""              $route;
    "true"          "nginx3";
}

map $dynamic_target $chain_header {
    "app"           "";
    default         "true";
}

# Определяем заголовок, ip клиента + ip конечного nginx или всей цепочки nginx
map $http_x_internal_chain $final_x_forward_for {
    ""              "$remote_addr, $server_addr";
    "true"          "$http_x_forwarded_for, $server_addr";
}

geo $is_trusted {
    default 0;
    172.20.0.0/16 1; 
}

# Формируем чистый IP пользователя
map $is_trusted $temp_client_ip {
    0       $remote_addr;
    1       $http_x_real_ip;
}


map $temp_client_ip $first_client_ip {
    ""      $remote_addr;
    default $temp_client_ip;
}


server {
    listen 80;
    server_name _;

    location / {

        proxy_set_header X-Real-IP $first_client_ip;
        proxy_set_header X-Forwarded-For $final_x_forward_for;
        proxy_set_header X-Internal-Chain $chain_header;

        proxy_pass http://$dynamic_target:80;
    }
}

